matrix:
  include:
    - language: go
      go: 1.13.x
      install: true
      script:
        - ./test.sh
      deploy:
        # deploy binaries
        - provider: script
          skip_cleanup: true
          script: curl -sL https://git.io/goreleaser | bash
          on:
            tags: true
            condition: $TRAVIS_OS_NAME = linux

        # deploy API
        - provider: heroku
          api_key: $HEROKU_PRODUCTION_API_KEY
          app: $HEROKU_APP_NAME
        
    - language: node_js
      node_js: 10
      env:
        - REPLACE="#!\/usr\/bin\/env\ node"
      script:
        - npm i -g @stoplight/cli
        #- sed -i "1s/.*/$REPLACE/" $(npm config get prefix)/lib/node_modules/@stoplight/cli/bin/stoplight.js
      deploy:
        # deploy docs
        - provider: script
          skip_cleanup: true
          script: $(npm config get prefix)/bin/stoplight publish --token $STOPLIGHT_TOKEN --url https://stoplight.io/api
        

notifications:
  email: false
